services:
  api:
    build:
      context: ./Bartender.Api
    container_name: bartender-api
    restart: always
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      # Example connection string if you add a db container:
      Default: ${Default}
    networks:
      - default
      - shared-net

  web:
    build:
      context: ./bartender-client
    restart: always
    ports:
      - "8088:80"   # hostPort:containerPort
    depends_on:
      - api
    networks:
      - default
      - shared-net

networks:
  default:
    name: bartender-net
  shared-net:
    external: true

dns:
  - 192.168.0.20